# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto_general', models.CharField(max_length=1000)),
                ('foto_general', models.ImageField()),
                #('texto', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                #('archivada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
